---
output: html_document
title: "Diffusion Map, using ForceAtlas to display results"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(plotly)
require(crosstalk)
require(data.table)
require(dplyr)
require(htmltools)
require(FNN)
require(ForceAtlas2)
corr <- fread("shiny_app/geno_correlation.r2", key=c("p1", "p2"))
options(warn = -1)

# Create a function for the diffusion map embedding.
diffusion_map_embedding <- function(affinity, k, t)
{
	d <- rowSums(affinity)
	markov <- affinity / d
	ev <- eigen(markov)
	idx <- order(abs(ev$values), decreasing=TRUE)
	e <- ev$values[idx]
	v <- ev$vectors[,idx]

	mat <- matrix(nrow=nrow(affinity), ncol=k)

	for (i in 2:(k+1)) {
		mat[,(i-1)] <- v[,i] * (e[i] ** t)
	}

	return(mat)
}

```

Here we use the squared genetic correlation matrix as the affinity matrix, and compute a Nonlinear dimensionality reduction. We then project this onto the plane using the R package `ForceAtlas`.

<br>

```{r corr_alphabet, echo=FALSE, warning=FALSE}

# Uncomment to evaluate the embedding, if it has already been generated just load it in.
storeWarn<- getOption("warn")
options(warn = -1) 
i_max <- length(levels(factor(corr$p1)))+1
phenotypes <- c(corr$p1[1], corr$p2[1:i_max-1])
phenotypes_translation <- c(corr$description_p1[1], corr$description_p2[1:i_max-1])
corr_matrix <- matrix(0, nrow=i_max, ncol=i_max)
p_matrix <- matrix(0, nrow=i_max, ncol=i_max)
h2_matrix <- matrix(0, nrow=i_max, ncol=i_max)
se_matrix <- matrix(0, nrow=i_max, ncol=i_max)

# Correlation matrix
corr_matrix[lower.tri(corr_matrix)] <- corr$rg
corr_matrix[which(lower.tri(corr_matrix), arr.ind=TRUE)[,c(2,1)]] <- corr$rg
diag(corr_matrix) <- 1

# # Using the diffusion map for 40 components, create the weights and use the force atlas package.
# affinity <- corr_matrix ** 2
# diff_embed <- Re(diffusion_map_embedding(affinity, 40, 1))
# nw <- get.knn(diff_embed, k=40)
# df_nw <- data.frame(from=rep(seq(1,nrow(nw$nn.index))),
# 	to=as.vector(nw$nn.index),
# 	weights=1)

# atlasproj <- layout.forceatlas2(df_nw, directed=FALSE, iterations = 5000, plotstep = 100)
# atlasproj$name <- paste(phenotypes, phenotypes_translation, sep=" : ")
# save('atlasproj', file='shiny_app/atlasproj.Rdata')
load('shiny_app/atlasproj.Rdata')

ax <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE,
  ticks = ''
)

# DEV: add in the axis labels.
p <- div(plot_ly(
  atlasproj, x = ~V1, y = ~V2,
  type = 'scatter',
  mode = 'markers',
  # Hover text:
  text = atlasproj$name,
  # color = ~carat, size = ~carat
  hoverinfo='text',
  width=800, height=800
) %>% layout(xaxis = ax, yaxis = ax), align='center')
p
```
</div>