---
title: "Genetic correlation between traits and disorders in the UK Biobank"
output: html_document
---

<br>

<div class="well">

To build upon the existing work in which we generated additive heritability estimates across the UK biobank traits, we have now generated and curated a collection of genetic correlations between each of traits and disorders.

The subset of traits that we host here represent the collection of traits with medium or high confidence of significant $h^2$ as detailed in (insert link). Please click below to explore the results and download the data!

<br>

<div style="text-align: center;">
<a href="rg_browser.html" class="btn btn-primary btn-lg">Browse  $r_g$</a>
<a href="plots_home.html" class="btn btn-primary btn-lg">Explore Plots</a>
<a href="https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0"  class="btn btn-primary btn-lg" onclick="trackOutboundLink('https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0'); return false;">Download Results</a>
</div>

<br>

For further information, please feel free to **contact us at: <nealelab.ukb@gmail.com>.**

</div>

<div class="well">

#### FAQ

**Where can I find the heritability results?**

We’ve built a [browser](rg_browser.html) to allow you to peruse the results. You can also download the full correlation results file <a href="https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0" onclick="trackOutboundLink('https://www.dropbox.com/sh/g28ee03vy4hvqw5/AADAkDbSFHsYE8bme1Jjeekca/ldsc_results?dl=0'); return false;">full correlation results file</a>.

**What method have you used to estimate genetic correlation?**

We use [LD score regression to estimate genetic correlation](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4495769/). Full code and technical details are available in the [github repository](https://github.com/bulik/ldsc).

**Are the primary GWAS results used for this analysis available? **

Absolutely! GWAS results are [available for download](https://sites.google.com/broadinstitute.org/ukbbgwasresults/). Please check out [this introductory post](http://www.nealelab.is/blog/2017/7/19/rapid-gwas-of-thousands-of-phenotypes-for-337000-samples-in-the-uk-biobank) for much more information. 

</div>

<div class="well">

#### Credits

**Genetic correlation analysis team:**

Liam Abbott,
Sam Bryant,
Claire Churchhouse,
Benjamin Neale,
Duncan Palmer.

**Neale Lab UKBB team:**

Liam Abbott,
Jon Bloom,
Sam Bryant,
Claire Churchhouse,
Andrea Ganna,
Jackie Goldstein,
Daniel Howrigan,
Dan King,
Benjamin Neale,
Duncan Palmer,
Tim Poterba,
Cotton Seed,
Raymond Walters.

</div>