---
output: html_document
params:
  pheno: "50"
  dat: "shiny_app/geno_corr_no_irnt_label.Rdata"
# title: "Genetic correlations with `r params$pheno`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(plotly)
require(crosstalk)
require(data.table)
require(dplyr)
require(DT)
require(kableExtra)
require(formattable)
# handle params
phen <- as.character(params$pheno)
print(phen)
load(params$dat)
# setup
dat_pheno <- geno_corr_df[.(params$pheno)]
ukcode <- strsplit(phen,"_")[[1]][1]
isICD <- is.na(as.numeric(ukcode))

if (isICD) {
	ukb_url = "http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=41202"
	ukcode = "41202"
} else {
	ukb_url = paste0("http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=", ukcode)
}

# Jobs
# get rid of `irnt`.
# include the phenotypic correlation as a matrix.
# include the difference between them as a matrix.
# also need to incorporate male and female results as separate pages.
# want a phenotype specific table too, which you can naivigate - this won't be big so can easily include using Raymonds methods.
# want to run UMAP.
# want to run PCA.
# Include all the relevant links to the UK biobank website. 
# Ideally, want the numbers associated to each phenotype...would need to parse the summary file for that.
# Want to add titles etc to the plotly plots that I created that say what everything is.
# Get rid of the gross buttons....or at the very least, figure out how to centre them.
# Could play with kable here.

```

<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css">
<script src="http://code.jquery.com/jquery-2.1.2.min.js"></script>
<script src="http://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $("table").DataTable();
    } );
</script>

<br>

### Genetic correlations with [`r dat_pheno$description_p1[1]`](`r ukb_url`)

Genetic correlation is estimated using [LD-score regression](https://github.com/bulik/ldsc). Full details of the correlation estimator can be found [here](https://www.ncbi.nlm.nih.gov/pubmed/26414676).


```{r make_plot, echo=FALSE}
div_colors <- c('blue','white','red')
which <- order(dat_pheno$rg)[c(1:20, (nrow(dat_pheno)-80):nrow(dat_pheno))]
dat_pheno <- dat_pheno[which,]
dat_pheno$logp <- -log10(dat_pheno$p)
dat_pheno$p2_tmp <- factor(paste0(dat_pheno$p2,':',dat_pheno$description_p2),
	levels = paste0(dat_pheno$p2,':',dat_pheno$description_p2)[order(dat_pheno$rg, decreasing = TRUE)])
colfunc <- colorRampPalette(c("blue", "white", "red"))
pal <- colfunc(1000)[round(ifelse(dat_pheno$rg< -1, 1, ifelse(dat_pheno$rg > 1, 1000, dat_pheno$rg*1000+1000)/2))]

# define barplot
pp <- plot_ly(dat_pheno, height=600) %>%
			add_trace(
			  x=~p2_tmp,
			  y=~rg,
			  marker = list(color =  pal),
			  hoverinfo="text",
			  text=~paste0(p1, " : ", p2, "\n",
			  	description_p1, " : ", description_p2, "\n",
			  	"Correlation : ", signif(rg, 3), "\n",
			  	"p-value: ", signif(p, 3)),
			  type="bar"
	  ) %>% layout(
	  			 showlegend=FALSE,
	  			 xaxis = list(title="", tickangle=-90, automargin=TRUE, showticklabels=FALSE),
	  			 yaxis = list(title="$r_g$",side='left', range=c(-1,1))
	  )
	bscols(widths=c(12),
		   config(pp, collaborate=FALSE, showLink=FALSE, displayModeBar=FALSE, displaylogo=FALSE, sendData=FALSE, mathjax = "cdn")
		  )
```
<div class="well">

```{r make_table, echo=FALSE}

	dat_pheno <- geno_corr_df[.(params$pheno)]
	ukcode <-  sapply(strsplit(dat_pheno$p2, split='_'),`[`, 1)
	isPHESANT <- grepl('^[0-9]', ukcode)
	uk_site <- ifelse(isPHESANT, paste0("http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=", ukcode),
		"http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=41202")
	n <- nrow(dat_pheno)
	n_tests <- n * (n-1) / 2
	bonf_thres <- 0.05 / n_tests
	nominal <- 0.05

	dat_pheno$p2_site <- ifelse(isPHESANT, paste0("<a href='", uk_site, "'>", dat_pheno$p2,"</a>"), dat_pheno$p2)
  	dat_pheno$description_p2 <- paste0("<a href='rg_summary_", dat_pheno$p2,".html'>", dat_pheno$description_p2,"</a>")
  	dat_pheno$description_p2 <- paste0("<a href='rg_summary_", dat_pheno$p2,".html'>", dat_pheno$description_p2,"</a>")
	dat_pheno <- dat_pheno %>% rename("ID" = p2_site, "Phenotype" = description_p2) %>% select(c("ID", "Phenotype", "rg", "p"))

	dat_pheno %>% mutate(
		"\\(r_g\\)" = ifelse(rg <= 0.0, color_tile("cornflowerblue", "transparent")(round(rg, 2)*c(rg<=0)),
							   color_tile("transparent", "indianred3")(round(rg,2)*c(rg>=0))),
		"\\(p\\)" = ifelse(p < bonf_thres, cell_spec(format(p, digits = 2), bold = TRUE),
                   ifelse(p > nominal, cell_spec(format(p, digits = 2)),
                   		  cell_spec(format(p, digits = 2), italic = TRUE)))) %>% select(c("ID", "Phenotype", "\\(r_g\\)", "\\(p\\)")) %>% 
    kable(escape=FALSE, align=c("l","l","c","c")) %>% kable_styling("hover", protect_latex=TRUE)

```

</div>